### ISSUE TITLE
Fix formatting of related post component

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#984] opened 2020-03-11 13:49 UTC
The formatting of the related post component is broken:

![rel-post](https://user-images.githubusercontent.com/1510/76423527-3d753080-63a7-11ea-87c2-4bc325a8568d.png)

Unfortunately I'm not able to reproduce this quickly in Safari or Chrome so we'll need to find out what that is broken in Percy only or in which browsers in which versions with which viewport sizes it is broken and then fix it accordingly.

**Comment by locks** [comment] 2020-03-11 15:30
Can't reproduce in Firefox either.

**Comment by marcoow** [comment] 2020-03-11 15:49
It seems it's possible/required to upgrade Chrome manually on Percy – I just did that so let's see how the next build renders

**Comment by marcoow** [comment] 2020-03-11 16:28
This is a pre-rendering problem – I can reproduce when I run the pre-rendered site and disable rehydration:

<img width="1795" alt="Bildschirmfoto 2020-03-11 um 17 27 56" src="https://user-images.githubusercontent.com/1510/76440180-c26b4480-63bd-11ea-86cf-4aeb9477b3b6.png">

**Comment by locks** [comment] 2020-03-11 18:09
Closed by #990.

**Closed as completed by locks** 2020-03-11 18:09 UTC
